my_django_proj/book_manager/urls.py
# encoding: utf-8
"""
@project = Py_learing
@file = urls
@author= wanghu
@create_time = 2021/11/30 15:07
"""
from django.urls import path
from book_manager import views

# app_name = 'book_manager'

urlpatterns = [
    path('index', views.index, name='index'),
    path('add_book', views.add_book, name='add_book'),
    path('book_detail', views.handle_book, name='book_detail'),
]

my_django_proj/my_django_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', include('test_django.urls')),
    path('bookmanager/', include('book_manager.urls')),
]

my_django_proj/test_django/urls.py
# encoding: utf-8
"""
@project = Py_learing
@file = urls
@author= wanghu
@create_time = 2021/11/24 14:35
"""
from django.urls import path
from test_django import views

# 链接反转时需要指定命令空间
app_name = 'test_django'

urlpatterns = [
    path('index', views.echo_index, name='shouye'),
    path('login', views.echo_login, name='denglu'),
    path('param/<int:pid>', views.test_param, name='param'),
    path('kw', views.test_kw, name='kw'),
    path('render', views.echo_render, name='render'),
    path('render/p/1', views.echo_com_render, name='render_1'),
    path('templates', views.echo_template, name='tmplt')
]

my_django_proj/book_manager/models.py
from django.db import models

# Create your models here.

my_django_proj/book_manager/views.py
from django.shortcuts import render
from django.db import connection

def get_cursor():
    return connection.cursor()

def index(request):
    cursor = get_cursor()
    cursor.execute('select id,book_name,author from `django_data`')
    data = cursor.fetchall()
    books = {"data": data}
    return render(request, 'index.html', context=books)

def add_book(request):
    return render(request, 'add_book.html')

def handle_book(request):
    pass

my_django_proj/test_django/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect, reverse
from django.shortcuts import render

# Create your views here.
def test_param(request, pid):
    return HttpResponse('获取到了链接中参数是pid:%s' % pid)

def test_kw(request):
    kw = request.GET.get('kw')
    return HttpResponse('获取到了链接中的查询字符串为：%s' % kw)

def echo_index(request):
    username = request.GET.get('username')
    if username:
        return HttpResponse('这是首页！')
    else:
        return redirect(reverse('test_django:denglu'))

def echo_login(request):
    return HttpResponse('这是登录页面！')

def echo_render(request):
    param = {
        'user': 'wanghu',
        'age': '22',
    }
    return render(request, 'render.html', context=param)

def echo_com_render(request):
    param = {
        'users': [{
                'username': 'wanghu',
                'age': 22,
                'account': 'suitang',
                'psswd': '123456', },
             {
                 'username': '王虎',
                 'age': 24,
                 'account': 'suitang123',
                 'psswd': '123456', },
            ]
    }
    return render(request, 'render_1.html', context=param)

def echo_template(request):
    return render(request, 'tmplt.html')

my_django_proj/templates/add_book.html
{% extends 'header.html' %}
{% block content %}
<p>书名:<input></p>
<p>作者:<input></p>
<button type="submit">提交</button>
{% endblock %}

my_django_proj/templates/book_detail.html
{% extends 'header.html' %}

my_django_proj/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>简易的图书管理系统</title>
    <link rel="stylesheet" href="{% static 'book_manager/header.css' %}">
</head>
<body>
    <nav>
        <ul class="nav">
            <li><a href="{% url 'index' %}">首页</a></li>
            <li><a href="{% url 'add_book' %}">发布图书</a></li>
        </ul>
    </nav>
    {% block content %}

    {% endblock %}
</body>
</html>

my_django_proj/templates/index.html
{% extends 'header.html' %}
{% block content %}
    <table>
        <thead>
        <tr>
            <th>序号</th>
            <th>书名</th>
            <th>作者</th>
        </tr>
        </thead>
        <tbody>
            {% for book in data %}
            <tr>
                <td>{{ book.0 }}</td>
                <td>{{ book.1 }}</td>
                <td>{{ book.2 }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

my_django_proj/templates/render.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>这是我的render页面</title>
</head>
<body>
<h1>This is a Test!</h1>
<p style="background-color: #fc1626">Hello, {{ user }}!您的年龄是:{{ age }}</p>
</body>
</html>

my_django_proj/templates/render_1.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <style>
        .nav{
            top: 25px;
            right: 0;
            position: fixed;
            overflow: hidden;
            float: right;
        }
        .ul{
            list-style: none;
            margin: 0 20px;
        }
    </style>
    <meta charset="UTF-8">
    <title>比较复杂的template测试</title>
</head>
<body>
<p style="background: green">开始咯!</p>

<div>
    {% if username == '王虎' %}
    <p>您好!{{ age }}岁的{{ username }}会员!</p>
    {% else %}
    <p>对不起!请先登录!</p>
    {% endif %}
    {% with wh=users.1.username %}
    <p>您好！会员{{ wh }},欢迎登录!</p>
    {% endwith %}
</div>
<div>
    {% for user in users %}
        {% for k,v in user.items %}
            <li>{{ k}}</li>
            <li>{{ v }}</li>
        {% endfor %}
    {% endfor %}
</div>
<div class="nav">
    <p>友情链接</p>
    <div class="ul">
        <a href="{% url 'test_django:render' %}">render</a>
        <a href="{% url 'test_django:denglu' %}">denglu</a>
        <a href="{% url 'test_django:param' pid='1' %}">param</a>
        <a href="{% url 'test_django:kw' %}?kw=123456">kw</a>
        <a href="{% url 'test_django:shouye' %}">shouye</a>
    </div>
</div>
</body>
</html>

my_django_proj/templates/tmplt.html
<!--{% load static %}-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<img src="{% static 'logo.jpg' %}" alt=""><p>Hello World!</p>
</body>
</html>